[build]
  command = "npm run build"
  publish = "dist"

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "src/_data"

    # All the feeds we wish to gather for use in the build
    [[plugins.inputs.feeds]]
      name = "RELEVANT"
      url = "https://www.relevantmagazine.com/feed/"
      ttl = 10800   # Cache for 3 hours
    [[plugins.inputs.feeds]]
      name = "Christianity Today News"
      url = "http://feeds.christianitytoday.com/christianitytoday/ctmag/"
      ttl = 86400   # Cache for 24 hours
    [[plugins.inputs.feeds]]
      name = "Christianity Today Hot Topics"
      url = "http://feeds.christianitytoday.com/christianitytoday/hottopics/"
      ttl = 86400   # Cache for 24 hours
    [[plugins.inputs.feeds]]
      name = "Christianity Today Most Reads"
      url = "http://feeds.christianitytoday.com/christianitytoday/mostreads/"
      ttl = 86400   # Cache for 24 hours
    [[plugins.inputs.feeds]]
      name = "Christianity Today Movie Features"
      url = "http://feeds.christianitytoday.com/christianitytoday/moviefeatures/"
      ttl = 86400   # Cache for 24 hours    
    [[plugins.inputs.feeds]]
      name = "Christianity Today Music Features"
      url = "http://feeds.christianitytoday.com/christianitytoday/musicfeatures/"
      ttl = 120   # Cache for 2 minutes   
